app:
    import:
        demande:
            mapping:
                id:                            A
                idClientDemande:               B
                type:                          C
                objet:                         D
                responsable:                   E
                priority:                      F
                dateDebut:                     G
                dateFin:                       H
                chargeTotal:                   I