app:
    import:
        demande:
            mapping:
                idClientDemande:               A
                type:                          B
                objet:                         C
                responsable:                   D
                application:                   E
                priority:                      F
                dateDebut:                     G
                dateFin:                       H
                chargeTotal:                   I