app:
    import:
        demande:
            mapping:
                idClientDemande:               B
                type:                          C
                objet:                         A
                responsable:                   E
                application:                   F
                priority:                      G
                dateDebut:                     H
                dateFin:                       I
                chargeTotal:                   J